domain/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url

from views import (
    DomainListView,
    DomainDeleteView,
    DomainAddView,
    DomainEditView,
)


urlpatterns = [
    # url(r'^test/$', TestView.as_view(), name='domain-test'),
    url(r'^list/$', DomainListView.as_view(), name='domain-list'),
    url(r'^add/$', DomainAddView.as_view(), name='domain-add'),
    url(r'^delete/(?P<pk>\d+)/$', DomainDeleteView.as_view(), name='domain-delete'),
    url(r'^edit/(?P<pk>\d+)/$', DomainEditView.as_view(), name='domain-edit'),
]

navi/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url

from views import NaviListView, NaviManageView, NaviAddView, NaviDeleteView, NaviEditView
from navi import views

# NAVI API
from rest_framework import routers
from api import NAVIViewSet

# Register NAVI API
router = routers.DefaultRouter()
router.register(r'navi', NAVIViewSet)


urlpatterns = [
    url(r'^$', NaviListView.as_view(), name='navi-index'),
    url(r'^manage/', NaviManageView.as_view(), name='navi-manage'),
    url(r'^add/', NaviAddView.as_view(), name='navi-add'),
    url(r'^delete/(?P<pk>\d+)/$', NaviDeleteView.as_view(), name='navi-delete'),
    url(r'^edit/(?P<pk>\d+)/$', NaviEditView.as_view(), name='navi-edit'),
]

youth/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
""" URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

from assets.urls import router as assets_router
from rest_framework.schemas import get_schema_view
from rest_framework.documentation import include_docs_urls

schema_view = get_schema_view(title="CMDB API")


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/navi'), name='index'),
    url(r'^user/', include('users.urls', namespace='user')),
    url(r'^navi/', include('navi.urls', namespace='navi')),
    url(r'^permission/', include('permission.urls', namespace='permission')),
    url(r'^asset/', include('assets.urls', namespace='assets')),
    url(r'^domain/', include('domain.urls', namespace='domain')),

    # 资产API
    url(r'^api/', include(assets_router.urls)),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^docs/', include_docs_urls(title="CMDB Api Docs")),
    url('^schema/$', schema_view),
]

domain/models.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-


from __future__ import unicode_literals
import django.utils.timezone as timezone
from django.db import models

ADD_AREA = (
    (str(1), u"dnspod"),
    (str(2), u"company-dns"),
    (str(3), u"azure-dnsmasq")
    )


class Domain(models.Model):
    domain_name = models.URLField(u"域名名称")
    ip = models.GenericIPAddressField(u"解析IP", max_length=15)
    env = models.CharField(u"使用环境", max_length=50, null=True, blank=True)
    add_area = models.CharField(u"添加位置", choices=ADD_AREA, max_length=30, null=True, blank=True)
    usage = models.CharField(u"用途", max_length=50)
    applicant = models.CharField(u"申请人", max_length=50)
    add_time = models.DateTimeField(u"添加时间", default = timezone.now)
    expiration_time = models.DateTimeField(u"过期时间", max_length=200, null=True, blank=True)

    def __unicode__(self):
        return self.domain_name

    class Meta:
        verbose_name = u'域名管理'
        verbose_name_plural = verbose_name
        db_table = 'domain'

        permissions = (
            ("can_add_domain", "添加域名"),
            ("can_change_domain", "修改域名"),
            ("can_delete_domain", "删除域名"),
            ("can_view_domain", "查看域名"),
        )

domain/forms.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from django import forms
from django.forms.widgets import *

from .models import Domain


class DomainForm(forms.ModelForm):

    class Meta:
        model = Domain
        exclude = ("id","add_time","expiration_time")

        widgets = {
            'domain_name': TextInput(attrs={'class': 'form-control','style': 'width:450px;', 'placeholder': u'域名名称，必填项'}),
            'ip': TextInput(attrs={'class': 'form-control','style': 'width:450px;', 'placeholder': u'解析IP，必填项'}),
            'env': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;', 'placeholder': u'使用环境，可选填'}),
            'add_area': Select(attrs={'class': 'form-control', 'style': 'width:450px;', 'placeholder': u'添加位置'}),
            'usage': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;', 'placeholder': u'用途，必填项'}),
            'applicant': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;', 'placeholder': u'申请人，必填项'}),
        }

domain/views.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from django.shortcuts import render, HttpResponse
import json
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.views.generic.list import ListView, View
from django.views.generic.edit import DeleteView, CreateView, UpdateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models import Q

from models import Domain, ADD_AREA
from forms import DomainForm

# Create your views here.


class DomainListView(PermissionRequiredMixin, LoginRequiredMixin, ListView):
    model = Domain
    context_object_name = "domains"
    template_name = 'domain/domain_list.html'
    paginate_by = 6
    http_method_names = ['get','post']
    permission_required = 'domain.can_view_domain'
    raise_exception = True

    def get_queryset(self):
        object_list = Domain.objects.all().order_by('-add_time')

        add_area = self.request.GET.get('add_area',"")
        keyword = self.request.GET.get('keyword',"")
        if add_area:
            object_list = object_list.filter(add_area__contains = add_area)

        if keyword:
            object_list = object_list.filter(
            Q(domain_name__contains = keyword) |
            Q(ip__contains=keyword) |
            Q(applicant__contains=keyword))
        return object_list

    def get_context_data(self, **kwargs):
        context = super(DomainListView, self).get_context_data(**kwargs)
        add_area_num = self.request.GET.get('add_area', "")
        keyword = self.request.GET.get('keyword',"")

        add_area = ADD_AREA
        context['add_area'] = add_area
        context['add_area_num'] = add_area_num
        context['keyword'] = keyword
        return context



class DomainAddView(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    model = Domain
    # 如果指定了form_class，则不能指定 fields
    # fields = ['name','description','url','memo']
    form_class = DomainForm
    template_name = "domain/domain_add.html"
    success_url = reverse_lazy('domain:domain-list')
    permission_required = 'domain.can_add_domain'
    raise_exception = True


class DomainDeleteView(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Domain
    success_url = reverse_lazy('domain:domain-list')
    permission_required = 'domain.can_delete_domain'
    raise_exception = True

    # 重写dispatch方法，在返回之前，加ajax请求判断
    def dispatch(self, *args, **kwargs):
        resp = super(DomainDeleteView, self).dispatch(*args, **kwargs)
        if self.request.is_ajax():
            return JsonResponse({"results": "ok"})
        else:
            return resp


class DomainEditView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    model = Domain
    form_class = DomainForm
    template_name = "domain/domain_edit.html"
    success_url = reverse_lazy('domain:domain-list')
    permission_required = 'domain.can_change_domain'
    raise_exception = True

templates/domain/domain_add.html
{% extends 'base.html' %}
$.ajaxSetup({
　　data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
});

{% block self_head_css_js %}
    <script>
        window.onload=init;
        function init() {
            showhide();
        }
        function showhide() {
            $('#domain').addClass('active menu-open')
            $('#domain-list').addClass('active')
        }
    </script>
{% endblock %}


{% block page_header %}
    <!-- Content Header (内容header) -->
    <section class="content-header">
        <h1>
            域名添加
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">域名管理</a></li>
            <li class="active">域名添加</li>
        </ol>
    </section>
{% endblock %}

{% block main_content %}
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">添加域名条目</h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fa fa-minus"></i></button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fa fa-times"></i></button>
                </div>
            </div>
            <div class="box-body">
                <form action="{% url 'domain:domain-add' %}" method="post">
{#                    {% csrf_token %}#}
{#                    {{ form.as_p }}#}
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.errors %}
                            <div class="form-group has-error" >
                        {% else %}
                            <div class="form-group">
                        {% endif %}

                        {{ field.label_tag }}
                        {{ field }}
                        {% for error in field.errors %}
                            <span class="label label-danger">{{ error }}</span>
                        {% endfor %}
                        </div>
                    {% endfor %}



                    <input type="submit" class="btn btn-primary" style="width: 60pt" value="提交">&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="{% url 'domain:domain-list' %}"><li style="width: 60pt" class="btn btn-primary" value="">返回</li></a><br>
                </form>
            </div>
            <!-- /.box-body -->
            <div class="box-footer">
                <i class="fa fa-info-circle"></i> 请勿重复添加条目
            </div>
            <!-- /.box-footer-->
        </div>
        <!-- /.box -->
    </section>


{% endblock %}


{% block link_js %}
    <!-- 页面JS Start -->
{#<!-- DataTables -->#}


    <!-- 页面JS End -->
{% endblock %}

templates/domain/domain_edit.html
{% extends 'base.html' %}
$.ajaxSetup({
　　data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
});

{% block self_head_css_js %}
    <script>
        window.onload=init;
        function init() {
            showhide();
        }
        function showhide() {
            $('#domain').addClass('active menu-open')
            $('#domain-list').addClass('active')
        }
    </script>



{% endblock %}


{% block page_header %}
    <!-- Content Header (内容header) -->
    <section class="content-header">
        <h1>
            域名编辑条目
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">域名管理</a></li>
            <li class="active">域名编辑</li>
        </ol>
    </section>
{% endblock %}

{% block main_content %}
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">域名编辑条目</h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fa fa-minus"></i></button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fa fa-times"></i></button>
                </div>
            </div>
            <div class="box-body">
                <form action="{% url 'domain:domain-edit' domain.id %}" method="post">
{#                    {% csrf_token %}#}
{#                    {{ form.as_p }}#}
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.errors %}
                            <div class="form-group has-error" >
                        {% else %}
                            <div class="form-group">
                        {% endif %}

                        {{ field.label_tag }}
                        {{ field }}
                        {% for error in field.errors %}
                            <span class="label label-danger">{{ error }}</span>
                        {% endfor %}
                        </div>
                    {% endfor %}


                    <input type="submit" class="btn btn-primary" style="width: 60pt" value="提交">&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="{% url 'domain:domain-list' %}"><li style="width: 60pt" class="btn btn-primary" value="">返回</li></a><br>
                </form>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </section>


{% endblock %}


{% block link_js %}
    <!-- 页面JS Start -->
{#<!-- DataTables -->#}


    <!-- 页面JS End -->
{% endblock %}

templates/domain/domain_list.html
{% extends 'base.html' %}
{% load static %}


{% block page_header %}
    <!-- Content Header (内容header) -->
    <section class="content-header">
        <h1>
            域名管理
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">域名管理</a></li>
            <li class="active">域名管理</li>
        </ol>
    </section>
{% endblock %}

{% block main_content %}
    <!-- Main content -->
    <section class="content">
        <form action="" method="get" id="domain_form">
            <div class="box">
                <div class="box-header">
                    <div class="col-sm-2" style="padding-left: 0">
                        <a href="{% url 'domain:domain-add' %}">
                            <li class="btn btn btn-primary">
                                <b>添加</b>
                            </li>
                        </a>
                    </div>
                {{ add_area_num }}
                    <div class="col-sm-5" style="padding-left: 0px">
                        <label>
                            <select name="add_area" class="form-control m-b input-sm" onchange="change_info()">
                                <option value="">添加位置（筛选）</option>
                                {% for i in add_area %}
                                    {% ifequal i.0 request.GET.add_area %}
                                        <option value="{{ i.0 }}" selected> {{ i.1 }}</option>
                                    {% else %}
                                        <option value="{{ i.0 }}"> {{ i.1 }}</option>
                                    {% endifequal %}
                                {% endfor %}
                            </select>
                        </label>

                    </div>
                    <div class="col-sm-4" style="padding-right: 0;">
                        <div class="input-group inline-group padding-right: 10px">
                            <input type="text" class="form-control m-b" name="keyword" value="{{ request.GET.keyword }}" placeholder="Search">
                            <input type="text" style="display: none">
                            <div class="input-group-btn ">
                                <button type="submit" class="btn btn-primary" onclick="change_info()">
                                    <b>搜索</b>
                                </button>
                                <a href="#" onclick="return export_excel()">
                                    <li name="export" class="btn btn-success search-btn-excel">
                                        <b>导出</b>
                                    </li>
                                </a>
                            </div>
                        </div>
                    </div>
                    <div id="export"></div>
                </div>


                <!-- /.box-header -->
                <div class="box-body">
                    <table id="dataform" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>域名</th>
                            <th>IP</th>
                            <th>环境</th>
                            <th>添加位置</th>
                            <th>用途</th>
                            <th>申请人</th>
                            <th class="text-center">功能</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% if domains %}
                            {% for domain in domains %}
                                <tr>
                                    <td>
                                        <a href="">{{ domain.domain_name }}</a>
                                    </td>
                                    <td>{{ domain.ip }}</td>
                                    <td>{{ domain.env }}</td>
                                    <td>{{ domain.get_add_area_display }}</td>
                                    <td>{{ domain.usage }}</td>
                                    <td>{{ domain.applicant }}</td>

                                    <td class="text-center" data-editable='false'>
                                        <a class="edit btn btn-sm btn-info" name="edit" href="{% url 'domain:domain-edit' domain.id %}">编辑</a>
                                        <a class="delete btn btn-sm btn-danger" name="delete" href="{% url 'domain:domain-delete' domain.id %}">删除</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        {% else %}
                            <p>No Item are available.</p>
                        {% endif %}
                        </tbody>
                    </table>
                {{ is_paginated }}
                    {% if is_paginated %}
                        <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="paginate_button"><a href="?page={{ page_obj.previous_page_number }}">上一页</a></li>
                        {% else %}
                            <li class="paginate_button disabled"><a href="">上一页</a></li>
                        {% endif %}

                            <li class="paginate_button">
                                <a href="">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a>
                            </li>

                            {% if page_obj.has_next %}
                                <li class="paginate_button"><a href="?page={{ page_obj.next_page_number }}">下一页</a></li>
                            {% else %}
                                <li class="paginate_button disabled"><a href="">下一页</a></li>
                            {% endif %}
                        </ul>
                    {% endif %}

                    <div class="btn-group">
{#                        <button class="btn btn-danger" style="width: 60pt;font-size: medium" onclick="return checkSubmit()">#}
{#                            <b>删除</b>#}
{#                        </button>#}
                    </div>
                </div>
            </div>
        </form>
    </section>

{% endblock %}

{% block custom_foot_js %}
<!-- DataTables -->
    <script src="{% static 'bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/bootbox/bootbox.js' %}"></script>
    <script>
        window.onload=init;
        function init() {
            showhide();
        }
        function showhide() {
            $('#domain').addClass('active menu-open')
            $('#domain-list').addClass('active')
        }

        $(document).ready(function() {
            var table = $('#dataform').DataTable( {
                "paging": false,
                "lengthChange": true,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": true
            } );

            $(".checkBtn").click(function(){
                  var checkValue = $(this).val();
                  if (this.checked){
                      $("." + checkValue).fadeIn();
                  } else {
                      $("." + checkValue).fadeOut();
                  }
              });
        } );

    </script>
    <script>
    function change_info(){
        var args = $("#domain_form").serialize();
        console.log(args);
        window.location = "{% url 'domain:domain-list' %}?" + args
    }


{#    function export_excel(){#}
{#        var asset_id_all = getIDall();#}
{#        if (asset_id_all == ''){#}
{#            if(confirm('您没有勾选，是否导出全部信息？')){#}
{#                var args = $("#asset_form").serialize();#}
{#                window.location = "{% url 'cmdb' %}?export=all&" + args#}
{#                }else{#}
{#                    return false;#}
{#                }#}
{#            }else{#}
{#                var args = $("#asset_form").serialize();#}
{#                window.location = "{% url 'cmdb' %}?export=true&" + args#}
{#            }#}
{#    }#}
{#    $("#search_input").keydown(function(e) {#}
{#        if (e.keyCode == 13) {#}
{#            change_info()#}
{#        }#}
{#        });#}
</script>

    <script>
        $.ajaxSetup({
            data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
        });
        $(document).ready(function () {
            $(".delete").click(function () {
                if(confirm('确定删除吗？')){
                    $.post(this.href, function (data) {
                        if (data.results = "ok") {
                            window.location.reload();
                        } else {
                            alert("sth wrong");
                        }
                    });
                }
                return false;
            })
        })

    </script>
{% endblock %}






templates/domain/test.html
{% extends 'base.html' %}
{% load static %}


{% block page_header %}
    <!-- Content Header (内容header) -->
    <section class="content-header">
        <h1>
            域名管理
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">域名管理</a></li>
            <li class="active">域名管理</li>
        </ol>
    </section>
{% endblock %}

{% block main_content %}
    <!-- Main content -->
    <section class="content">
        <form action="" method="post">
            {% csrf_token %}
            <div class="box">
                <div class="box-header">
                    <div class="btn-group">
                        <a href="{% url 'domain:domain-add' %}">
                            <li class="btn btn-success" style="width: 60pt;font-size: medium" >
                                <b>添加</b>
                            </li>
                        </a>
                    </div>
                </div>
{{ all_domains }}
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="dataform" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>域名</th>
                            <th>IP</th>
                            <th>环境</th>
                            <th>添加位置</th>
                            <th>用途</th>
                            <th>申请人</th>
                            <th class="text-center">功能</th>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </form>
    </section>

{% endblock %}

{% block custom_foot_js %}
<!-- DataTables -->
    <script src="{% static 'bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/bootbox/bootbox.js' %}"></script>
    <script>
        window.onload=init;
        function init() {
            showhide();
        }
        function showhide() {
            $('#domain').addClass('active menu-open')
            $('#domain-list').addClass('active')
        }

        $(document).ready(function() {
            var table = $('#dataform').DataTable( {
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": true,
                "processing": true,
                "serverSide": true,
                "ajax": {
                    "url": "/domain/test/",
                    "type": "get"
                },
                "columns": [
                    {"data": "id"},
                    {"data": "song"},
                    {"data": "singer"},
                    {"data": "last_modify_date"},
                    {"data": "created"},
                    {
                        "data": null,
                        "defaultContent": '<button type="button" class="btn btn-info">Edit</button>' + '&nbsp;&nbsp' +
                        '<button type="button" class="btn btn-danger">Delete</button>'
                    }
                ]
            });

            $(".checkBtn").click(function(){
                  var checkValue = $(this).val();
                  if (this.checked){
                      $("." + checkValue).fadeIn();
                  } else {
                      $("." + checkValue).fadeOut();
                  }
              });
        } );

    </script>
    <script>
        $.ajaxSetup({
            data: {csrfmiddlewaretoken: '{{ csrf_token }}' },
        });
        $(document).ready(function () {
            $(".delete").click(function () {
                if(confirm('确定删除吗？')){
                    $.post(this.href, function (data) {
                        if (data.results == "ok") {
                            window.location.reload();
                        } else {
                            alert("sth wrong");
                        }
                    });
                }
                return false;
            })
        })

    </script>
{% endblock %}




