assets/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url, include

from rest_framework.routers import DefaultRouter


from assets import views
from assets import api


router = DefaultRouter()
router.register(r'idcs', api.IdcViewSet)
router.register(r'assetgroups', api.AssetGroupViewSet)
router.register(r'assets', api.AssetViewSet)

urlpatterns = [
    # Asset
    url(r'^host/list/$', views.AssetListView.as_view(), name='asset-list'),
    url(r'^host/add/$', views.AssetAddView.as_view(), name='asset-add'),
    url(r'^host/delete/(?P<pk>\d+)/$', views.AssetDeleteView.as_view(), name='asset-delete'),
    url(r'^host/edit/(?P<pk>\d+)/$', views.AssetEditView.as_view(), name='asset-edit'),

    # IDC
    url(r'^idc/list/$', views.IdcListView.as_view(), name='idc-list'),
    url(r'^idc/add/', views.IdcAddView.as_view(), name='idc-add'),
    url(r'^idc/delete/(?P<pk>\d+)/$', views.IdcDeleteView.as_view(), name='idc-delete'),
    url(r'^idc/edit/(?P<pk>\d+)/$', views.IdcEditView.as_view(), name='idc-edit'),

    # AssetGroup
    url(r'^group/list/$', views.AssetGroupListView.as_view(), name='asset-group-list'),
    url(r'^group/add/', views.AssetGroupAddView.as_view(), name='asset-group-add'),
    url(r'^group/delete/(?P<pk>\d+)/$', views.AssetGroupDeleteView.as_view(), name='asset-group-delete'),
    url(r'^group/edit/(?P<pk>\d+)/$', views.AssetGroupEditView.as_view(), name='asset-group-edit'),

    # Api信息

]

navi/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url

from views import NaviListView, NaviManageView, NaviAddView, NaviDeleteView, NaviEditView
from navi import views

# NAVI API
from rest_framework import routers
from api import NAVIViewSet

# Register NAVI API
router = routers.DefaultRouter()
router.register(r'navi', NAVIViewSet)


urlpatterns = [
    url(r'^$', NaviListView.as_view(), name='navi-index'),
    url(r'^manage/', NaviManageView.as_view(), name='navi-manage'),
    url(r'^add/', NaviAddView.as_view(), name='navi-add'),
    url(r'^delete/(?P<pk>\d+)/$', NaviDeleteView.as_view(), name='navi-delete'),
    url(r'^edit/(?P<pk>\d+)/$', NaviEditView.as_view(), name='navi-edit'),
]

youth/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
""" URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

from assets.urls import router as assets_router
from rest_framework.schemas import get_schema_view
from rest_framework.documentation import include_docs_urls

schema_view = get_schema_view(title="CMDB API")


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/navi'), name='index'),
    url(r'^user/', include('users.urls', namespace='user')),
    url(r'^navi/', include('navi.urls', namespace='navi')),
    url(r'^permission/', include('permission.urls', namespace='permission')),
    url(r'^asset/', include('assets.urls', namespace='assets')),
    url(r'^domain/', include('domain.urls', namespace='domain')),

    # 资产API
    url(r'^api/', include(assets_router.urls)),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^docs/', include_docs_urls(title="CMDB Api Docs")),
    url('^schema/$', schema_view),
]

assets/forms.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from django import forms
from django.forms.widgets import *

from .models import Assets, Idc, AssetGroup


class AssetForm(forms.ModelForm):

    class Meta:
        model = Assets
        exclude = ("id","add_time","update_time",)

        widgets = {
            'hostname': TextInput(attrs={'class': 'form-control','style': 'width:450px;', 'placeholder': u'主机名称，必填项'}),
            'ip': TextInput(attrs={'class': 'form-control','style': 'width:450px;', 'placeholder': u'IP地址，必填项 例如：8.8.8.8'}),
            'other_ip': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;', 'placeholder': u'外网IP，可选填'}),
            'asset_type': Select(attrs={'class': 'form-control', 'style': 'width:450px;', 'placeholder': u'设备类型，可选填'}),
            'status': Select(attrs={'class': 'form-control', 'style': 'width:450px;', 'placeholder': u'设备状态，可选填'}),
            'os': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;', 'placeholder': u'操作系统，可选填'}),
            'cpu_num': NumberInput(attrs={'class': 'form-control', 'style': 'width:450px;', 'placeholder': u'CPU数量，可选填'}),
            'memory': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;', 'placeholder': u'内存大小，可选填'}),
            'disk': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;', 'placeholder': u'硬盘信息，可选填'}),
            'sn': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;', 'placeholder': u'SN号码，可选填'}),
            'usage': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;', 'placeholder': u'机器用途，可选填'}),
            'application': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;', 'placeholder': u'装机软件，可选填'}),
            'principal': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;', 'placeholder': u'负责人，可选填'}),
            'memo': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;', 'placeholder': u'备注信息，可选填'}),
            'jira': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;', 'placeholder': u'申请jira，可选填'}),
            'group': Select(attrs={'class': 'form-control', 'style': 'width:450px;', 'placeholder': u'资产组，可选填'}),
            'idc': Select(attrs={'class': 'form-control', 'style': 'width:450px;', 'placeholder': u'所在机房，可选填'}),
        }


class IdcForm(forms.ModelForm):

    class Meta:
        model = Idc
        exclude = ("id",)

        widgets = {
            'name': TextInput(attrs={'class': 'form-control','style': 'width:450px;', 'placeholder': u'机房名称，必填项'}),
            'address': TextInput(attrs={'class': 'form-control','style': 'width:450px;', 'placeholder': u'机房地址，可选填'}),
            'tel': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;', 'placeholder': u'机房电话，可选填'}),
            'contact': TextInput(attrs={'class': 'form-control', 'style': 'width:450px;', 'placeholder': u'客户经理，可选填'}),
        }


class AssetGroupForm(forms.ModelForm):

    class Meta:
        model = AssetGroup
        exclude = ("id",)

        widgets = {
            'name': TextInput(attrs={'class': 'form-control','style': 'width:450px;', 'placeholder': u'主机组名称，必填项'}),
            'desc': TextInput(attrs={'class': 'form-control','style': 'width:450px;', 'placeholder': u'主机组描述，可选填'}),
        }

assets/views.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-

from django.http import JsonResponse
from django.db.models import Q
from django.views.generic.list import ListView
from django.views.generic import TemplateView
from django.views.generic.edit import DeleteView, CreateView, UpdateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.exceptions import ObjectDoesNotExist

from models import Assets, Idc, AssetGroup, ASSET_TYPE, ASSET_STATUS
from forms import AssetForm, IdcForm, AssetGroupForm

from permission.models import AssetPermission
from django.contrib.auth.models import User, Group

# Create your views here.


class AssetListView(PermissionRequiredMixin, LoginRequiredMixin, ListView):
    model = Assets
    context_object_name = "assets"
    template_name = 'assets/assets_list.html'
    permission_required = 'assets.can_view_asset'
    # raise_exception = True
    login_url = reverse_lazy('user:login')
    paginate_by = 5

    def get_queryset(self):
        asset_find = Assets.objects.all()
        # 获取前端get请求参数
        self.idc_name = self.request.GET.get('idc', '')
        self.group_name = self.request.GET.get('group', '')
        self.asset_type = self.request.GET.get('asset_type', '')
        self.status = self.request.GET.get('status', '')
        self.keyword = self.request.GET.get('keyword', '')
        # export = request.GET.get("export", '')

        # 通过前端get请求参数，筛选
        if self.idc_name:
            asset_find = asset_find.filter(idc__name__contains=self.idc_name)
        if self.group_name:
            asset_find = asset_find.filter(group__name__contains=self.group_name)
        if self.asset_type:
            asset_find = asset_find.filter(asset_type__contains=self.asset_type)
        if self.status:
            asset_find = asset_find.filter(status__contains=self.status)

        if self.keyword:
            asset_find = asset_find.filter(
            Q(hostname__icontains = self.keyword) |
            Q( ip__contains = self.keyword)
            )
        return asset_find

    def get_context_data(self, **kwargs):
        context = super(AssetListView, self).get_context_data(**kwargs)

        # 获取机房信息
        idc_info = Idc.objects.all()
        # 获取主机组信息
        group_info = AssetGroup.objects.all()

        # 返回前端需要的数据（机房信息、资产组信息、资产类型、资产状态、搜索关键字、匹配特定权限的具体资产信息）
        context = {
            'idc_name': self.idc_name,
            'group_name': self.group_name,
            'assettype': self.asset_type,
            'status': self.status,
            'keyword': self.keyword,

            'idc_info': idc_info,
            'group_info': group_info,
            'asset_type': ASSET_TYPE,
            'asset_status': ASSET_STATUS,
        }

        kwargs.update(context)
        return super(AssetListView, self).get_context_data(**kwargs)

# 按照资产组权限 进行展示，还没完善，代码先留在这里
# class AssetListView(PermissionRequiredMixin, LoginRequiredMixin, TemplateView):
#     # context_object_name = "assets"
#     template_name = 'assets/assets_list.html'
#     permission_required = 'assets.can_view_asset'
#     raise_exception = True
#     # login_url = reverse_lazy('user:login')
#     paginate_by = 2
#
#     def get_context_data(self, **kwargs):
#         # 获取当前登录用户user
#         current_user = self.request.user
#         # print current_user
#
#         # 如果是superuser 返回全部资产信息
#         if current_user.is_superuser:
#             asset_find = Assets.objects.all()
#
#         # 如果非superuser 查找对应权限 返回具有权限的资产信息
#         else:
#             # 通过user获取所在组，用户可能属于多个组，不能用get
#             current_group = Group.objects.filter(user=current_user)
#             # print current_group
#             # 获取用户组的 资产组权限, 可能是多个
#             user_group_permission = AssetPermission.objects.filter(group__in=current_group)
#
#             # 定义资产组列表
#             group_list = []
#             for i in user_group_permission:
#                 for assetgroup in i.assetsgroup.all():
#                     group_list.append(assetgroup)
#             asset_find = Assets.objects.filter(group__in=group_list)
#
#         # 获取机房信息
#         idc_info = Idc.objects.all()
#         # 获取主机组信息
#         group_info = AssetGroup.objects.all()
#
#         # 获取前端get请求参数
#         idc_name = self.request.GET.get('idc', '')
#         group_name = self.request.GET.get('group', '')
#         asset_type = self.request.GET.get('asset_type', '')
#         status = self.request.GET.get('status', '')
#         keyword = self.request.GET.get('keyword', '')
#
#         # 通过前端get请求参数，筛选
#         if idc_name:
#             asset_find = asset_find.filter(idc__name__contains=idc_name)
#         if group_name:
#             asset_find = asset_find.filter(group__name__contains=group_name)
#         if asset_type:
#             asset_find = asset_find.filter(asset_type__contains=asset_type)
#         if status:
#             asset_find = asset_find.filter(status__contains=status)
#
#         if keyword:
#             asset_find = asset_find.filter(
#             Q(hostname__icontains=keyword) |
#             Q( ip__contains=keyword)
#             )
#
#         # 返回前端需要的数据（机房信息、资产组信息、资产类型、资产状态、搜索关键字、匹配特定权限的具体资产信息）
#         context = {
#             'idc_name': idc_name,
#             'group_name': group_name,
#             'assettype': asset_type,
#             'status': status,
#             'keyword': keyword,
#
#             'idc_info': idc_info,
#             'group_info': group_info,
#             'asset_type': ASSET_TYPE,
#             'asset_status': ASSET_STATUS,
#             'assets': asset_find
#         }
#
#         kwargs.update(context)
#         return super(AssetListView, self).get_context_data(**kwargs)


class AssetAddView(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    model = Assets
    # 如果指定了form_class，则不能指定 fields
    # fields = ['name','description','url','memo']
    form_class = AssetForm
    template_name = "assets/assets_add.html"
    success_url = reverse_lazy('assets:asset-list')
    permission_required = 'assets.can_add_asset'
    raise_exception = True


class AssetDeleteView(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Assets
    success_url = reverse_lazy('assets:asset-list')
    permission_required = 'assets.can_delete_asset'
    raise_exception = True

    # 重写dispatch方法，在返回之前，加ajax请求判断
    def dispatch(self, *args, **kwargs):
        resp = super(AssetDeleteView, self).dispatch(*args, **kwargs)
        if self.request.is_ajax():
            return JsonResponse({"results": "ok"})
        else:
            return resp


class AssetEditView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    model = Assets
    form_class = AssetForm
    template_name = "assets/assets_edit.html"
    success_url = reverse_lazy('assets:asset-list')
    permission_required = 'assets.can_change_asset'
    raise_exception = True


class IdcListView(PermissionRequiredMixin, LoginRequiredMixin, ListView):
    model = Idc
    context_object_name = "idcs"
    template_name = 'assets/idc_list.html'
    permission_required = 'assets.can_view_idc'
    raise_exception = True


class IdcAddView(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    model = Idc
    # 如果指定了form_class，则不能指定 fields
    # fields = ['name','description','url','memo']
    form_class = IdcForm
    template_name = "assets/idc_add.html"
    success_url = reverse_lazy('assets:idc-list')
    permission_required = 'assets.can_add_idc'
    raise_exception = True


class IdcDeleteView(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    model = Idc
    success_url = reverse_lazy('assets:idc-list')
    permission_required = 'assets.can_delete_idc'
    raise_exception = True

    # 重写dispatch方法，在返回之前，加ajax请求判断
    def dispatch(self, *args, **kwargs):
        resp = super(IdcDeleteView, self).dispatch(*args, **kwargs)
        if self.request.is_ajax():
            return JsonResponse({"results": "ok"})
        else:
            return resp


class IdcEditView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    model = Idc
    form_class = IdcForm
    template_name = "assets/idc_edit.html"
    success_url = reverse_lazy('assets:idc-list')
    permission_required = 'assets.can_change_idc'
    raise_exception = True


class AssetGroupListView(PermissionRequiredMixin, LoginRequiredMixin, ListView):
    model = AssetGroup
    context_object_name = "assetgroups"
    template_name = 'assets/asset_group_list.html'
    permission_required = 'assets.can_view_assetgroup'
    raise_exception = True


class AssetGroupAddView(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    model = AssetGroup
    # 如果指定了form_class，则不能指定 fields
    # fields = ['name','description','url','memo']
    form_class = AssetGroupForm
    template_name = "assets/asset_group_add.html"
    success_url = reverse_lazy('assets:asset-group-list')
    permission_required = 'assets.can_add_assetgroup'
    raise_exception = True


class AssetGroupDeleteView(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    model = AssetGroup
    success_url = reverse_lazy('assets:asset-group-list')
    permission_required = 'assets.can_delete_idc'
    raise_exception = True

    # 重写dispatch方法，在返回之前，加ajax请求判断
    def dispatch(self, *args, **kwargs):
        resp = super(AssetGroupDeleteView, self).dispatch(*args, **kwargs)
        if self.request.is_ajax():
            return JsonResponse({"results": "ok"})
        else:
            return resp


class AssetGroupEditView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    model = AssetGroup
    form_class = AssetGroupForm
    template_name = "assets/asset_group_edit.html"
    success_url = reverse_lazy('assets:asset-group-list')
    permission_required = 'assets.can_change_assetgroup'
    raise_exception = True

templates/assets/asset_group_add.html
{% extends 'base.html' %}

{% block page_header %}
    <section class="content-header">
        <h1>
            资产组管理
            <small>资产组管理（增删改查）</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">资产组管理</a></li>
            <li class="active">资产组添加</li>
        </ol>
    </section>
{% endblock %}

{% block main_content %}
    <!-- Main content -->
    <section class="content">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">添加主机组</h3>
                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fa fa-minus"></i></button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fa fa-times"></i></button>
                </div>
            </div>
            <div class="box-body">
                <form action="{% url 'assets:asset-group-add' %}" method="post">
                    {% csrf_token %}
{#                    {{ form.as_p }}#}
                    {% for field in form %}
                        {% if field.errors %}
                            <div class="form-group has-error" >
                        {% else %}
                            <div class="form-group">
                        {% endif %}

                        {{ field.label_tag }}
                        {{ field }}
                        {% for error in field.errors %}
                            <span class="label label-danger">{{ error }}</span>
                        {% endfor %}
                        </div>
                    {% endfor %}



                    <input type="submit" class="btn btn-primary" style="width: 60pt" value="提交">&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="{% url 'assets:asset-group-list' %}"><li style="width: 60pt" class="btn btn-primary" value="">返回</li></a><br>
                </form>
            </div>

            <div class="box-footer">
                <i class="fa fa-info-circle"></i> 请勿重复添加条目
            </div>
        </div>
    </section>


{% endblock %}


{% block self_css_js %}
    <script>
        window.onload=init;
        function init() {
            showhide();
        }
        function showhide() {
            $('#asset').addClass('active menu-open');
            $('#asset-group-list').addClass('active')
        }
    </script>
{% endblock %}

templates/assets/asset_group_list.html
{% extends 'base.html' %}
{% load static %}

{% block page_header %}
    <section class="content-header">
        <h1>
            资产组管理
            <small>资产组管理（增删改查）</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">资产组管理</a></li>
            <li class="active">资产组列表</li>
        </ol>
    </section>
{% endblock %}

{% block main_content %}
    <!-- Main content -->
    <section class="content">
        <form action="" method="post">
            {% csrf_token %}
            <div class="box">
                <div class="box-header">
                    <div class="btn-group">
                        <a href="{% url 'assets:asset-group-add' %}">
                            <button type="button" class="btn btn-success">添加</button>
                        </a>
                    </div>
                    <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fa fa-minus"></i></button>
                    <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fa fa-times"></i></button>
                </div>
                </div>

                <div class="box-body">
                    <table id="dataform" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>主机组名称</th>
                            <th>主机组描述</th>
                            <th class="text-center">功能</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% if assetgroups %}
                            {% for assetgroup in assetgroups %}
                                <tr>
                                    <td><a href="{% url 'assets:asset-group-edit' assetgroup.id %}">{{ assetgroup.name }}</a></td>
                                    <td class="asset_type">{{ assetgroup.desc }}</td>
                                    <td class="text-center" data-editable='false'>
                                        <a class="edit btn btn-sm btn-info" name="edit" href="{% url 'assets:asset-group-edit' assetgroup.id %}">编辑</a>
                                        <a class="delete btn btn-sm btn-danger" name="delete"  href="{% url 'assets:asset-group-delete' assetgroup.id %}">删除</a>

                                    </td>
                                </tr>
                            {% endfor %}
                        {% else %}
                            <p>No Item are available.</p>
                        {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </form>
    </section>

{% endblock %}


{% block self_css_js %}
    <!-- DataTables -->
    <script src="{% static 'plugins/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>


    <script>
        // 高亮显示菜单
        window.onload=init;
        function init() {
            showhide();
        }
        function showhide() {
            $('#asset').addClass('active menu-open');
            $('#group-list').addClass('active')
        }

        // 初始化datatables
        $(function () {
            $('#dataform').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false
            });
        });

    </script>
    <script>
        // 删除
        $.ajaxSetup({
            data: {
                csrfmiddlewaretoken: '{{ csrf_token }}'
            }
        });
        $(document).ready(function () {
            $(".delete").click(function () {
                if(confirm('确定删除吗？')){
                    $.post(this.href, function (data) {
                        if (data.results = "ok") {
                            window.location.reload();
                        } else {
                            alert("sth wrong");
                        }
                    });
                }
                return false;
            })
        })

    </script>
{% endblock %}









templates/assets/idc_list.html
{% extends 'base.html' %}
{% load static %}

{% block page_header %}
    <section class="content-header">
        <h1>
            机房管理
            <small>机房管理（增删改查）</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">资产</a></li>
            <li class="active">机房列表</li>
        </ol>
    </section>
{% endblock %}

{% block main_content %}
    <!-- Main content -->

    <section class="content">
        <form action="" method="post">
            {% csrf_token %}
            <div class="box">
                <div class="box-header">
                    <div class="btn-group">
                        <a href="{% url 'assets:idc-add' %}">
                            <button type="button" class="btn btn-success">添加</button>
                        </a>
                    </div>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                            <i class="fa fa-minus"></i></button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                            <i class="fa fa-times"></i></button>
                    </div>
                </div>

                <div class="box-body">
                    <table id="dataform" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th class="name">机房名称</th>
                            <th class="ip">机房地址</th>
                            <th class="asset_type">机房电话</th>
                            <th class="group">客户经理</th>
                            <th class="text-center">功能</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% if idcs %}
                            {% for idc in idcs %}
                                <tr>
                                    <td><a href="{% url 'assets:idc-edit' idc.id %}">{{ idc.name }}</a></td>
                                    <td>{{ idc.address }}</td>
                                    <td>{{ idc.tel }}</td>
                                    <td>{{ idc.contact }}</td>
                                    <td class="text-center" data-editable='false'>
                                        <a class="edit btn btn-sm btn-info" name="edit" href="{% url 'assets:idc-edit' idc.id %}">编辑</a>
                                        <a class="delete btn btn-sm btn-danger" name="delete"  href="{% url 'assets:idc-delete' idc.id %}">删除</a>

                                    </td>
                                </tr>
                            {% endfor %}
                        {% else %}
                            <p>No Item are available.</p>
                        {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </form>
    </section>

{% endblock %}


{% block self_css_js %}
    <!-- DataTables -->
    <script src="{% static 'plugins/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>


    <script>
        // 高亮显示菜单
        window.onload=init;
        function init() {
            showhide();
        }
        function showhide() {
            $('#asset').addClass('active menu-open');
            $('#idc-list').addClass('active')
        }

        // 初始化datatables
        $(function () {
            $('#dataform').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false
            });
        });

    </script>
    <script>
        // 删除
        $.ajaxSetup({
            data: {
                csrfmiddlewaretoken: '{{ csrf_token }}'
            }
        });
        $(document).ready(function () {
            $(".delete").click(function () {
                if(confirm('确定删除吗？')){
                    $.post(this.href, function (data) {
                        if (data.results = "ok") {
                            window.location.reload();
                        } else {
                            alert("sth wrong");
                        }
                    });
                }
                return false;
            })
        })

    </script>
{% endblock %}





