assets/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url, include

from rest_framework.routers import DefaultRouter


from assets import views
from assets import api


router = DefaultRouter()
router.register(r'idcs', api.IdcViewSet)
router.register(r'assetgroups', api.AssetGroupViewSet)
router.register(r'assets', api.AssetViewSet)

urlpatterns = [
    # Asset
    url(r'^host/list/$', views.AssetListView.as_view(), name='asset-list'),
    url(r'^host/add/$', views.AssetAddView.as_view(), name='asset-add'),
    url(r'^host/delete/(?P<pk>\d+)/$', views.AssetDeleteView.as_view(), name='asset-delete'),
    url(r'^host/edit/(?P<pk>\d+)/$', views.AssetEditView.as_view(), name='asset-edit'),

    # IDC
    url(r'^idc/list/$', views.IdcListView.as_view(), name='idc-list'),
    url(r'^idc/add/', views.IdcAddView.as_view(), name='idc-add'),
    url(r'^idc/delete/(?P<pk>\d+)/$', views.IdcDeleteView.as_view(), name='idc-delete'),
    url(r'^idc/edit/(?P<pk>\d+)/$', views.IdcEditView.as_view(), name='idc-edit'),

    # AssetGroup
    url(r'^group/list/$', views.AssetGroupListView.as_view(), name='asset-group-list'),
    url(r'^group/add/', views.AssetGroupAddView.as_view(), name='asset-group-add'),
    url(r'^group/delete/(?P<pk>\d+)/$', views.AssetGroupDeleteView.as_view(), name='asset-group-delete'),
    url(r'^group/edit/(?P<pk>\d+)/$', views.AssetGroupEditView.as_view(), name='asset-group-edit'),

    # Api信息

]

navi/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url

from views import NaviListView, NaviManageView, NaviAddView, NaviDeleteView, NaviEditView
from navi import views

# NAVI API
from rest_framework import routers
from api import NAVIViewSet

# Register NAVI API
router = routers.DefaultRouter()
router.register(r'navi', NAVIViewSet)


urlpatterns = [
    url(r'^$', NaviListView.as_view(), name='navi-index'),
    url(r'^manage/', NaviManageView.as_view(), name='navi-manage'),
    url(r'^add/', NaviAddView.as_view(), name='navi-add'),
    url(r'^delete/(?P<pk>\d+)/$', NaviDeleteView.as_view(), name='navi-delete'),
    url(r'^edit/(?P<pk>\d+)/$', NaviEditView.as_view(), name='navi-edit'),
]

users/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url

from views import LoginView, LogoutView, UserListView, UserAddView, UserDeleteView, GroupListView


urlpatterns = [
    # 用户相关
    url(r'login/$',LoginView.as_view(), name='login'),
    url(r'logout/$', LogoutView.as_view(), name='logout'),

    url(r'^user/add/$', UserAddView.as_view(), name='user-add'),
    # url(r'^user/edit/(?P<pk>[0-9]+)/$',UserEditView.as_view(),name='user-edit'),
    url(r'^user/delete/(?P<pk>\d+)/$', UserDeleteView.as_view(), name='user-delete'),
    url(r'^user/list/$',UserListView.as_view(),name='user-list'),

    # 用户组相关
    # url(r'^group/add/$', UserAddView.as_view(), name='group-add'),
    # # url(r'^group/(?P<pk>[0-9]+)/update/$',UserUpdate.as_view(),name='group-update'),
    # url(r'^group/delete/(?P<pk>\d+)/$', UserDeleteView.as_view(), name='group-delete'),
    url(r'^group/list/$',GroupListView.as_view(),name='group-list'),
]

youth/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
""" URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

from assets.urls import router as assets_router
from rest_framework.schemas import get_schema_view
from rest_framework.documentation import include_docs_urls

schema_view = get_schema_view(title="CMDB API")


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/navi'), name='index'),
    url(r'^user/', include('users.urls', namespace='user')),
    url(r'^navi/', include('navi.urls', namespace='navi')),
    url(r'^permission/', include('permission.urls', namespace='permission')),
    url(r'^asset/', include('assets.urls', namespace='assets')),
    url(r'^domain/', include('domain.urls', namespace='domain')),

    # 资产API
    url(r'^api/', include(assets_router.urls)),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^docs/', include_docs_urls(title="CMDB Api Docs")),
    url('^schema/$', schema_view),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<!-- Header -->
{% include 'head_script.html' %}
{% block self_head_css_js %} {% endblock %}

<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    <!-- Navbar -->
    {% include 'header.html' %}

    <!-- Main Sidebar Container -->
    {% include 'sidebar.html' %}

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        {% block page_header %}
            <section class="content-header">
                <h1>
                    Blank page
                    <small>it all starts here</small>
                </h1>
                <ol class="breadcrumb">
                    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                    <li><a href="#">Examples</a></li>
                    <li class="active">Blank page</li>
                </ol>
            </section>
        {% endblock %}

        <!-- Main content -->
        {% block main_content %}
            <!-- Main content -->
            <section class="content">

                <!-- Default box -->
                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Title</h3>

                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                                <i class="fa fa-minus"></i></button>
                            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                                <i class="fa fa-times"></i></button>
                        </div>
                    </div>

                    <div class="box-body">
                        Start creating your amazing application!
                    </div>
                </div>

                <div class="box-footer">
                    Footer
                </div>
            </section>

        {% endblock %}
    </div>

    <!-- Footer -->
    {% include 'footer.html' %}

    <!-- Control Sidebar -->
    {% include 'control.html' %}

</div>

<!-- jQuery 3 -->
<script src="{% static 'plugins/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'plugins/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- SlimScroll -->
<script src="{% static 'plugins/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'plugins/fastclick/lib/fastclick.js' %}"></script>
<!-- AdminLTE App -->
<script src=" {% static 'js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'js/demo.js' %}"></script>
<script>
    $(document).ready(function () {
        $('.sidebar-menu').tree()
    })
</script>

{% block self_css_js %} {% endblock %}

</body>

</html>

templates/control.html
  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
      <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>

      <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
      <!-- Home tab content -->
      <div class="tab-pane" id="control-sidebar-home-tab"></div>
      <div class="tab-pane" id="control-sidebar-stats-tab"></div>

      <!-- Settings tab content -->
      <div class="tab-pane" id="control-sidebar-settings-tab">
      </div>
    </div>
  </aside>
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>

templates/footer.html
 <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 2.0
    </div>
    <strong>Copyright &copy; 2018-2020 <a href="#">CMDB</a>.</strong> All rights
    reserved.
  </footer>

templates/head_script.html
{% load static %}
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AdminLTE 2 | Blank Page</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static 'plugins/bootstrap/dist/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/font-awesome/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'plugins/Ionicons/css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static 'css/skins/_all-skins.min.css' %}">

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>

templates/header.html
{% load static %}
  <header class="main-header">
    <!-- Logo -->
    <a href="#" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>You</b>th</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>CMDB</b>资产管理</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->
          <li class="dropdown messages-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-envelope-o"></i>
              <span class="label label-success">4</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 4 messages</li>
              <li>
                <!-- inner menu: contains the actual data -->
                <ul class="menu">
                  <li><!-- start message -->
                    <a href="#">
                      <div class="pull-left">
                        <img src="{% static 'img/user7-128x128.jpg' %}" class="img-circle" alt="User Image">
                      </div>
                      <h4>
                        Support Team
                        <small><i class="fa fa-clock-o"></i> 5 mins</small>
                      </h4>
                      <p>Why not buy a new awesome theme?</p>
                    </a>
                  </li>
                  <!-- end message -->
                </ul>
              </li>
              <li class="footer"><a href="#">See All Messages</a></li>
            </ul>
          </li>
          <!-- Notifications: style can be found in dropdown.less -->
          <li class="dropdown notifications-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-bell-o"></i>
              <span class="label label-warning">10</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 10 notifications</li>
              <li>
                <!-- inner menu: contains the actual data -->
                <ul class="menu">
                  <li>
                    <a href="#">
                      <i class="fa fa-users text-aqua"></i> 5 new members joined today
                    </a>
                  </li>
                </ul>
              </li>
              <li class="footer"><a href="#">View all</a></li>
            </ul>
          </li>
          <!-- Tasks: style can be found in dropdown.less -->
          <li class="dropdown tasks-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-flag-o"></i>
              <span class="label label-danger">9</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 9 tasks</li>
              <li>
                <!-- inner menu: contains the actual data -->
                <ul class="menu">
                  <li><!-- Task item -->
                    <a href="#">
                      <h3>
                        Design some buttons
                        <small class="pull-right">20%</small>
                      </h3>
                      <div class="progress xs">
                        <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar"
                             aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                          <span class="sr-only">20% Complete</span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <!-- end task item -->
                </ul>
              </li>
              <li class="footer">
                <a href="#">View all tasks</a>
              </li>
            </ul>
          </li>
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="{% static 'img/user7-128x128.jpg' %}" class="user-image" alt="User Image">
              <span class="hidden-xs">
                  {% if request.user %}
                      {{ request.user }}
                  {% endif %}
              </span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="{% static 'img/user7-128x128.jpg' %}" class="img-circle" alt="User Image">

                <p>
                  Alexander Pierce - Web Developer
                  <small>Member since Nov. 2012</small>
                </p>
              </li>
              <!-- Menu Body -->
              <li class="user-body">
                <div class="row">
                  <div class="col-xs-4 text-center">
                    <a href="#">Followers</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Sales</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Friends</a>
                  </div>
                </div>
                <!-- /.row -->
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">用户信息</a>
                </div>
                <div class="pull-right">
                  <a href="{% url 'user:logout' %}" class="btn btn-default btn-flat">爷走了</a>
                </div>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
          <li>
            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
          </li>
        </ul>
      </div>
    </nav>
  </header>

templates/link_css.html
{% load static %}
<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- SlimScroll -->
<script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'plugins/fastclick/fastclick.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'js/demo.js' %}"></script>

templates/sidebar.html
{% load static %}
  <!-- =============================================== -->

   <!-- Left side column. contains the sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="{% static 'img/user7-128x128.jpg' %}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>
              {% if request.user %}
                  {{ request.user }}
              {% endif %}
          </p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>

      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MAIN NAVIGATION</li>

        <li>
          <a href="#">
            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
            <span class="pull-right-container">
              <small class="label pull-right bg-red">Hot</small>
            </span>
          </a>
        </li>



          <li id="navi" class="treeview">
          <a href="#">
            <i class="fa fa-share"></i> <span>导航</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li id="navi-list"><a href="{% url 'navi:navi-index' %}"><i class="fa fa-circle-o"></i>导航列表</a></li>
            <li id="navi-manage"><a href="{% url 'navi:navi-manage' %}"><i class="fa fa-circle-o"></i>导航管理</a></li>
          </ul>
        </li>

        <li id="asset" class="treeview">
          <a href="#">
            <i class="fa fa-server"></i> <span>资产</span>

            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li id="asset-list">
                <a href="{% url 'assets:asset-list' %}"><i class="fa fa-circle-o"></i> 资产管理
                    <span class="pull-right-container">
                        <small class="label pull-right bg-green">400</small>
                    </span>
                </a>
              </li>
            <li id="asset-group-list"><a href="{% url 'assets:asset-group-list' %}"><i class="fa fa-circle-o"></i>资产组管理
                <span class="pull-right-container">
                    <small class="label pull-right bg-yellow">5</small>
                </span>
            </a>
            </li>
              <li id="idc-list"><a href="{% url 'assets:idc-list' %}"><i class="fa fa-circle-o"></i>机房管理
                <span class="pull-right-container">
                    <small class="label pull-right bg-red">2</small>
                </span>
              </a>
              </li>

          </ul>
        </li>

        <li id="user" class="treeview">
          <a href="#">
            <i class="fa fa-users"></i> <span>用户</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li id="user-list"><a href="{% url 'user:user-list' %}"><i class="fa fa-circle-o"></i>用户管理</a></li>
            <li id="group-list"><a href="{% url 'user:group-list' %}"><i class="fa fa-circle-o"></i>用户组管理</a></li>
{#              <li id="permission-list"><a href="{% url 'navi:navi-manage' %}"><i class="fa fa-circle-o"></i>权限管理</a></li>#}

          </ul>
        </li>

          <li id="permission" class="treeview">
          <a href="#">
            <i class="fa fa-shield"></i> <span>权限</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
              <li id="permission-list"><a href="{% url 'navi:navi-manage' %}"><i class="fa fa-circle-o"></i>用户组基础权限</a></li>
              <li id="permission-list"><a href="{% url 'navi:navi-manage' %}"><i class="fa fa-circle-o"></i>资产组授权</a></li>
          </ul>
        </li>

{#        <li class="treeview">#}
{#          <a href="#">#}
{#            <i class="fa fa-share"></i> <span>Multilevel</span>#}
{#            <span class="pull-right-container">#}
{#              <i class="fa fa-angle-left pull-right"></i>#}
{#            </span>#}
{#          </a>#}
{#          <ul class="treeview-menu">#}
{#            <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>#}
{#            <li class="treeview">#}
{#              <a href="#"><i class="fa fa-circle-o"></i> Level One#}
{#                <span class="pull-right-container">#}
{#                  <i class="fa fa-angle-left pull-right"></i>#}
{#                </span>#}
{#              </a>#}
{#              <ul class="treeview-menu">#}
{#                <li><a href="#"><i class="fa fa-circle-o"></i> Level Two</a></li>#}
{#                <li class="treeview">#}
{#                  <a href="#"><i class="fa fa-circle-o"></i> Level Two#}
{#                    <span class="pull-right-container">#}
{#                      <i class="fa fa-angle-left pull-right"></i>#}
{#                    </span>#}
{#                  </a>#}
{#                  <ul class="treeview-menu">#}
{#                    <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>#}
{#                    <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>#}
{#                  </ul>#}
{#                </li>#}
{#              </ul>#}
{#            </li>#}
{#            <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>#}
{#          </ul>#}
{#        </li>#}

        <li class="header">api视图与文档</li>
        <li><a href="/api"><i class="fa fa-circle-o text-red"></i> <span>API UI</span></a></li>
        <li><a href="/docs"><i class="fa fa-circle-o text-yellow"></i> <span>Documentation</span></a></li>
{#        <li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li>#}
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- =============================================== -->