navi/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url

from views import NaviListView, NaviManageView, NaviAddView, NaviDeleteView, NaviEditView
from navi import views

# NAVI API
from rest_framework import routers
from api import NAVIViewSet

# Register NAVI API
router = routers.DefaultRouter()
router.register(r'navi', NAVIViewSet)


urlpatterns = [
    url(r'^$', NaviListView.as_view(), name='navi-index'),
    url(r'^manage/', NaviManageView.as_view(), name='navi-manage'),
    url(r'^add/', NaviAddView.as_view(), name='navi-add'),
    url(r'^delete/(?P<pk>\d+)/$', NaviDeleteView.as_view(), name='navi-delete'),
    url(r'^edit/(?P<pk>\d+)/$', NaviEditView.as_view(), name='navi-edit'),
]

users/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url

from views import LoginView, LogoutView, UserListView, UserAddView, UserDeleteView, GroupListView


urlpatterns = [
    # 用户相关
    url(r'login/$',LoginView.as_view(), name='login'),
    url(r'logout/$', LogoutView.as_view(), name='logout'),

    url(r'^user/add/$', UserAddView.as_view(), name='user-add'),
    # url(r'^user/edit/(?P<pk>[0-9]+)/$',UserEditView.as_view(),name='user-edit'),
    url(r'^user/delete/(?P<pk>\d+)/$', UserDeleteView.as_view(), name='user-delete'),
    url(r'^user/list/$',UserListView.as_view(),name='user-list'),

    # 用户组相关
    # url(r'^group/add/$', UserAddView.as_view(), name='group-add'),
    # # url(r'^group/(?P<pk>[0-9]+)/update/$',UserUpdate.as_view(),name='group-update'),
    # url(r'^group/delete/(?P<pk>\d+)/$', UserDeleteView.as_view(), name='group-delete'),
    url(r'^group/list/$',GroupListView.as_view(),name='group-list'),
]

youth/urls.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
""" URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

from assets.urls import router as assets_router
from rest_framework.schemas import get_schema_view
from rest_framework.documentation import include_docs_urls

schema_view = get_schema_view(title="CMDB API")


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/navi'), name='index'),
    url(r'^user/', include('users.urls', namespace='user')),
    url(r'^navi/', include('navi.urls', namespace='navi')),
    url(r'^permission/', include('permission.urls', namespace='permission')),
    url(r'^asset/', include('assets.urls', namespace='assets')),
    url(r'^domain/', include('domain.urls', namespace='domain')),

    # 资产API
    url(r'^api/', include(assets_router.urls)),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^docs/', include_docs_urls(title="CMDB Api Docs")),
    url('^schema/$', schema_view),
]

users/models.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

from django.contrib.auth.models import AbstractUser


class UserProfile(AbstractUser):
    nick_name = models.CharField(max_length=20, verbose_name=u"昵称", default="")
    mobile = models.CharField(max_length=11, verbose_name=u"手机号码", null=True, blank=True)
    image = models.ImageField(upload_to="image/%Y/%m", default=u"image/default.png", max_length=100)

    class Meta:
        verbose_name = "用户信息"
        verbose_name_plural = verbose_name
        db_table = "users"

    def __unicode__(self):
        return self.username

    permissions = (
        ("can_add_user", "添加用户"),
        ("can_change_user", "修改用户"),
        ("can_delete_user", "删除用户"),
        ("can_view_user", "查看用户"),

        ("can_add_group", "添加用户组"),
        ("can_change_group", "修改用户组"),
        ("can_delete_group", "删除用户组"),
        ("can_view_group", "查看用户组"),
    )

users/forms.py
# -*- coding: utf-8 -*-

from django import forms
# from django.contrib.auth.models import User
from .models import UserProfile


class LoginForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True,min_length=5)


class UserAddForm(forms.Form):
    user = forms.CharField(
            required = True,
            label = u"用户名",
            error_messages = {'required': "请输入一个有效的用户"},
            max_length = 20,
            widget=forms.TextInput(
                attrs={'class': 'form-control', 'style': 'width:450px;', 'placeholder': u'输入用户，必填项'}
            )
    )
    newpassword1 = forms.CharField(
            required = True,
            label = u"输入密码",
            error_messages = {'required': "请输入你的密码"},
            widget = forms.PasswordInput(
                attrs = {'class': 'form-control', 'style': 'width:450px;', 'placeholder': u'输入密码，必填项'}
            )
        )
    newpassword2 = forms.CharField(
            required = True,
            label = u"再次输入密码",
            error_messages = {'required': "请再次输入你的密码"},
            widget = forms.PasswordInput(
                attrs = {'class': 'form-control', 'style': 'width:450px;', 'placeholder': u'确认密码，必填项'}
            )
        )
    email = forms.EmailField(
            required = True,
            label= u"邮箱",
            error_messages = {'required': "请输入有效的邮箱账号"},
            widget = forms.EmailInput(
            attrs = {'class': 'form-control', 'style': 'width:450px;', 'placeholder': u'注册邮箱，必填项'}
            )
        )
    mobile = forms.CharField(
        required = False,
        label = u"手机号码",
        error_messages={'required': "请输入手机号码"},
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'style': 'width:450px;', 'placeholder': u'手机号码，非必填项'}
        )
    )

    def clean(self):

        if self.cleaned_data['newpassword1'] != self.cleaned_data['newpassword2']:
            raise forms.ValidationError({
                # 'newpassword1':u"俩次密码输入不一致",
                 'newpassword2':u"俩次密码输入不一致"
            })
        elif self.cleaned_data['user']:
            if UserProfile.objects.filter(username = unicode(self.cleaned_data['user'])):
                raise forms.ValidationError({
                    'user':u"用户名已经注册！"
                })
        cleaned_data = super(UserAddForm, self).clean()
        return cleaned_data

users/views.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.http import JsonResponse

from django.db.models import Q
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.shortcuts import render,render_to_response,HttpResponseRedirect
from django.views.generic.base import View
from django.views.generic import FormView, DetailView, DeleteView, ListView, UpdateView, CreateView
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin

from django.contrib.auth.backends import ModelBackend
from django.contrib.auth.models import Group
from django.core.urlresolvers import reverse_lazy

from .models import UserProfile
from .forms import LoginForm, UserAddForm


class LoginView(View):
    """
    用户登录
    """
    def get(self,request):
        return render(request, 'users/login.html',{})

    def post(self,request):
        # 实例化
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            # 获取用户提交的用户名和密码
            user_name = request.POST.get('username', None)
            pass_word = request.POST.get('password', None)
            # print user_name
            # print pass_word
            # 成功返回user对象,失败None
            user = authenticate(username=user_name, password=pass_word)
            # 如果不是null说明验证成功
            if user is not None:
                if user.is_active:
                    # 只有注册激活才能登录
                    login(request, user)
                    return HttpResponseRedirect(reverse('index'))
                else:
                    return render(request, 'users/login.html', {'msg': '用户名或密码错误', 'login_form': login_form})
            # 只有当用户名或密码不存在时，才返回错误信息到前端
            else:
                return render(request, 'users/login.html', {'msg': '用户名或密码错误','login_form':login_form})

        # form.is_valid（）已经判断不合法了，所以这里不需要再返回错误信息到前端了
        else:
            return render(request,'users/login.html',{'login_form':login_form})


class LogoutView(View):
    """
    用户登出
    """
    def get(self,request):
        logout(request)
        return HttpResponseRedirect(reverse_lazy('user:login'))


class UserListView(PermissionRequiredMixin, LoginRequiredMixin, ListView):
    template_name = 'users/user_list.html'
    model = UserProfile
    context_object_name = "users"
    permission_required = 'users.can_view_user'
    login_url = reverse_lazy('user:login')


class UserAddView(PermissionRequiredMixin, LoginRequiredMixin, FormView):
    template_name = 'users/user_add.html'
    form_class = UserAddForm
    success_url = reverse_lazy('user:user-list')
    permission_required = 'users.can_add_user'

    def form_valid(self, form):
        username = form.cleaned_data['user']
        password = form.cleaned_data['newpassword1']
        email = form.cleaned_data['email']
        mobile = form.cleaned_data['mobile']
        UserProfile.objects.create_user(
            username = username,
            email = email,
            mobile = mobile,
            password = password,
            is_active = True,
            is_staff = True
        )
        return HttpResponseRedirect(self.get_success_url())


class UserDeleteView(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    model = UserProfile
    success_url = reverse_lazy('user:user-list')
    permission_required = 'users.can_delete_user'

    # 重写dispatch方法，在返回之前，加ajax请求判断
    def dispatch(self, *args, **kwargs):
        resp = super(UserDeleteView, self).dispatch(*args, **kwargs)
        if self.request.is_ajax():
            return JsonResponse({"results": "ok"})
        else:
            return resp


# class UserEditView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
#     template_name = 'users/user_edit.html'
#     model = UserProfile
#     form_class = UserAddForm
#     success_url = reverse_lazy('user:user-list')
#     permission_required = 'users.can_change_user'
#
#     def form_valid(self, form):
#         username = form.cleaned_data['user']
#         password = form.cleaned_data['newpassword1']
#         email = form.cleaned_data['email']
#         mobile = form.cleaned_data['mobile']
#         UserProfile.objects.create_user(
#             username=username,
#             email=email,
#             mobile=mobile,
#             password=password,
#             is_active=True,
#             is_staff=True
#         )
#         return HttpResponseRedirect(self.get_success_url())

class GroupListView(PermissionRequiredMixin, LoginRequiredMixin, ListView):
    template_name = 'users/group_list.html'
    model = Group
    context_object_name = "groups"
    permission_required = 'users.can_view_group'
    login_url = reverse_lazy('admin:login')






# # 邮箱和用户名都可以登录
# # 基于ModelBackend类，因为它有authenticate方法
# class CustomBackend(ModelBackend):
#     def authenticate(self, request, username=None, password=None, **kwargs):
#         try:
#             # 不希望用户存在两个，get只能有一个。两个是get失败的一种原因 Q为使用并集查询
#             user = User.objects.get(Q(username=username)|Q(email=username))
#
#             # django的后台中密码加密：所以不能password==password
#             # User 继承的AbstractUser中有def check_password(self, raw_password):
#             if user.check_password(password):
#                 return user
#         except Exception as e:
#             return None
#
#








#
#

#
#
# class GroupAddView(PermissionRequiredMixin, LoginRequiredMixin, FormView):
#     template_name = 'users/group_add.html'
#     form_class = GroupAddForm
#     success_url = reverse_lazy('permission:group-list')
#     permission_required = 'permission.can_add_group'
#     raise_exception = True
#
#     def form_valid(self, form):
#         name = form.cleaned_data['name']
#
#         User.objects.create_user(username=username,email=email,password=password,is_active=True,is_staff=True)
#         return HttpResponseRedirect(self.get_success_url())
#
#

templates/users/group_add.html
{% extends 'base.html' %}

{% block page_header %}
    <!-- Content Header (内容header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <!-- <h1>Blank Page</h1> -->
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">用户管理</a></li>
              <li class="breadcrumb-item active">用户添加</li>
            </ol>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

{% block main_content %}
    <!-- Main content -->
    <section class="content">
        <div class="card">
            <div class="card-header with-border">
                <h3 class="card-title">添加用户</h3>
            </div>
            <div class="card-body">
                <form action="{% url 'permission:user-add' %}" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}

                    <input type="submit" class="btn btn-primary" style="width: 60pt" value="提交">&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="{% url 'permission:user-list' %}"><li style="width: 60pt" class="btn btn-primary" value="">返回</li></a><br>
                </form>
            </div>
            <div class="card-footer">
                <i class="fa fa-info-circle"></i> 请勿重复添加条目
            </div>
        </div>
    </section>


{% endblock %}

{% block self_css_js %}
    <script>
        window.onload=init;
        function init() {
            showhide();
        }
        function showhide() {
            $('#user').addClass('menu-open');
            $('#user-list').addClass('active')
        }
    </script>

{% endblock %}

templates/users/group_list.html
{% extends 'base.html' %}
{% load static %}


{% block page_header %}
    <section class="content-header">
        <h1>
            用户组管理
            <small>用户管理组（增删改查）</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">用户组管理</a></li>
            <li class="active">用户组列表</li>
        </ol>
    </section>
{% endblock %}


{% block main_content %}
    <!-- Main content -->

    <section class="content">
        <form action="" method="post">
            {% csrf_token %}
            <div class="box">
                <div class="box-header">
                    <div class="btn-group">
                        <a href="{% url 'user:user-add' %}">
                            <li class="btn btn-success" style="width: 60pt;font-size: medium" >
                                <b>添加</b>
                            </li>
                        </a>
                    </div>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                            <i class="fa fa-minus"></i></button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                            <i class="fa fa-times"></i></button>
                    </div>
                </div>

                <div class="box-body">
                    <table id="dataform" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>用户组</th>

                            <th class="text-center">功能</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% if groups %}
                            {% for group in groups %}
                                <tr>
                                    <td>{{ group.name }}</td>
                                    <td class="text-center" data-editable='false'>
{#                                        <a class="edit btn btn-sm btn-info" name="edit" href="">编辑</a>#}
                                        <a class="delete btn btn-sm btn-danger" name="delete"  href="">删除</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        {% else %}
                            <p>No Item are available.</p>
                        {% endif %}
                        </tbody>
                    </table>
                    <div class="btn-group">
                    </div>
                </div>
            </div>
        </form>
    </section>

{% endblock %}


{% block self_css_js %}
    <!-- DataTables -->
    <script src="{% static 'plugins/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>



    <script>
        // 高亮显示菜单
        window.onload=init;
        function init() {
            showhide();
        }
        function showhide() {
            $('#user').addClass('active menu-open');
            $('#group-list').addClass('active')
        }

        // 初始化datatables
        $(function () {
            $('#dataform').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false
            });
        });

    </script>
    <script>
        // 删除
        $.ajaxSetup({
            data: {
                csrfmiddlewaretoken: '{{ csrf_token }}'
            }
        });
        $(document).ready(function () {
            $(".delete").click(function () {
                if(confirm('确定删除吗？')){
                    $.post(this.href, function (data) {
                        if (data.results = "ok") {
                            window.location.reload();
                        } else {
                            alert("sth wrong");
                        }
                    });
                }
                return false;
            })
        })

    </script>
{% endblock %}









templates/users/login.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>CMDB | Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static 'plugins/bootstrap/dist/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/font-awesome/css/font-awesome.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="{% static 'plugins/Ionicons/css/ionicons.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'css/AdminLTE.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'plugins/iCheck/square/blue.css' %}">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href=""><b>CMDB</b>资产管理系统</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Sign in to start your session</p>

    <form action="{% url 'user:login' %}" method="post">
        {% csrf_token %}
      <div class="form-group has-feedback">
        <input name="username" type="text" class="form-control" placeholder="用户名">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input name="password" type="password" class="form-control" placeholder="密码">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <input type="checkbox"> 记住我
            </label>
          </div>
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">登录</button>
        </div>
        <!-- /.col -->
      </div>
    </form>

    <!-- /.social-auth-links -->


  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

<!-- jQuery 3 -->
<script src="{% static 'plugins/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'plugins/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- iCheck -->
<script src="{% static 'plugins/iCheck/icheck.min.js' %}"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
    });
  });
</script>
</body>
</html>

templates/users/user_add.html
{% extends 'base.html' %}

{% block page_header %}
    <section class="content-header">
        <h1>
            用户管理
            <small>用户管理（增删改查）</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">用户管理</a></li>
            <li class="active">用户添加</li>
        </ol>
    </section>
{% endblock %}

{% block main_content %}
    <!-- Main content -->
    <section class="content">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">添加用户</h3>
                <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                            <i class="fa fa-minus"></i></button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                            <i class="fa fa-times"></i></button>
                    </div>
            </div>
            <div class="box-body">
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}

                    <input type="submit" class="btn btn-primary" style="width: 60pt" value="提交">&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="{% url 'user:user-list' %}"><li style="width: 60pt" class="btn btn-primary" value="">返回</li></a><br>
                </form>
            </div>
            <div class="box-footer">
                <i class="fa fa-info-circle"></i> 请勿重复添加条目
            </div>
        </div>
    </section>


{% endblock %}

{% block self_css_js %}
    <script>
        window.onload=init;
        function init() {
            showhide();
        }
        function showhide() {
            $('#user').addClass('active menu-open');
            $('#user-list').addClass('active')
        }
    </script>

{% endblock %}

templates/users/user_list.html
{% extends 'base.html' %}
{% load static %}

{% block page_header %}
    <section class="content-header">
        <h1>
            用户管理
            <small>用户管理（增删改查）</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">用户管理</a></li>
            <li class="active">用户列表</li>
        </ol>
    </section>
{% endblock %}


{% block main_content %}
    <!-- Main content -->

    <section class="content">
        <form action="" method="post">
            {% csrf_token %}
            <div class="box">
                <div class="box-header">
                    <div class="btn-group">
                        <a href="{% url 'user:user-add' %}">
                            <li class="btn btn-success" style="width: 60pt;font-size: medium" >
                                <b>添加</b>
                            </li>
                        </a>
                    </div>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                            <i class="fa fa-minus"></i></button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                            <i class="fa fa-times"></i></button>
                    </div>
                </div>

                <div class="box-body">
                    <table id="dataform" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>账户名</th>
                            <th>用户组</th>
                            <th>E-mail</th>
                            <th>手机号码</th>
                            <th>状态</th>
{#                            <th>最后登录时间</th>#}
                            <th class="text-center">功能</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% if users %}
                            {% for user in users %}
                            <tr>
                                <td>{{ user.username }}</td>
                                <td>
                                    {% for group in user.groups.all %}
                                        {{ group }}
                                    {% endfor %}
                                </td>
                                <td>{{ user.email }}</td>
                                <td>{{ user.mobile|default:"----" }}</td>
                                <td>
                                    {% if user.is_active %}
                                        <span class="label label-success">启用</span>
                                    {% else %}
                                        <span class="label label-default">禁用</span>
                                    {% endif %}
                                </td>
{#                                    <td>{{ user.last_login|date:"Y-m-d H:i:s" }}</td>#}
                                    <td class="text-center" data-editable='false'>
{#                                        <a class="edit btn btn-sm btn-info" name="edit" href="{% url 'user:user-edit' user.id %}">编辑</a>#}
                                        <a class="delete btn btn-sm btn-danger" name="delete" href="{% url 'user:user-delete' user.id %}">删除</a>
                                    </td>
                                </tr>
                            {% endfor %}
                        {% else %}
                            <p>No Item are available.</p>
                        {% endif %}
                        </tbody>
                    </table>
                    <div class="btn-group">
                    </div>
                </div>
            </div>
        </form>
    </section>

{% endblock %}


{% block self_css_js %}
    <!-- DataTables -->
    <script src="{% static 'plugins/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'plugins/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>


    <script>
        // 高亮显示菜单
        window.onload=init;
        function init() {
            showhide();
        }
        function showhide() {
            $('#user').addClass('active menu-open');
            $('#user-list').addClass('active')
        }

        // 初始化datatables
        $(function () {
            $('#dataform').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": true,
                "ordering": true,
                "info": true,
                "autoWidth": false
            });
        });

    </script>
    <script>
        // 删除
        $.ajaxSetup({
            data: {
                csrfmiddlewaretoken: '{{ csrf_token }}'
            }
        });
        $(document).ready(function () {
            $(".delete").click(function () {
                if(confirm('确定删除吗？')){
                    $.post(this.href, function (data) {
                        if (data.results = "ok") {
                            window.location.reload();
                        } else {
                            alert("sth wrong");
                        }
                    });
                }
                return false;
            })
        })

    </script>
{% endblock %}







